# Файл docker-compose.yml

# Перечень volume
volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    image: anmezer/taski_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
    restart: unless-stopped

  frontend:
    env_file: .env
    image: anmezer/taski_frontend
    volumes:
      - static:/frontend_static/
    command: cp -r /app/build/. /frontend_static/
    restart: on-failure

  gateway:
    image: anmezer/taski_gateway
    volumes:
      - static:/staticfiles
    ports:
      - 8000:80
    restart: unless-stopped